language: csharp
dist: trusty
sudo: false
dotnet: 2.1.401

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.14.0
    - os: osx
      osx_image: xcode9.3
      mono: 5.14.0

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_install:
  - dotnet tool install fake-cli -g
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.1/
  - mono .paket/paket.exe restore

script:
- fake build
