language: csharp
sudo: false  # use the new container-based Travis infrastructure 
install:
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
env: CONFIGS=Release
os: linux
dotnet: 2.1.4

matrix:
  include:
    - mono: latest
  exclude:
    - env: CONFIGS=Release

script: ./run tests
