language: csharp

env: CONFIGS=Release

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      mono: latest
    - os: linux
      sudo: required
      dist: trusty
      mono: none
      dotnet: 2.1.4
  exclude:
    - env: CONFIGS=Release

script: ./run tests
