language: csharp
sudo: false  # use the new container-based Travis infrastructure
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.1/
env: CONFIGS=Release
os: linux
dotnet: 2.1.4

matrix:
  include:
    - mono: latest
  exclude:
    - env: CONFIGS=Release

script: ./run tests
