#!/bin/bash -e

################################################################################

if hash xbuild &> /dev/null ; then
  BUILD=xbuild
  RUN=mono
  if hash fsharpiAnyCpu &> /dev/null ; then
    FSI=fsharpiAnyCpu
  else
    FSI=fsharpi
  fi
elif hash msbuild.exe &> /dev/null ; then
  BUILD="msbuild.exe /maxcpucount"
  RUN=
  FSI=fsianycpu.exe
else
  echo "Couldn't find build command."
  exit 1
fi

################################################################################

did() {
  local VAR=DID_$1
  if [ -z ${!VAR} ] ; then
    eval "$VAR=1"
    return 1
  else
    return 0
  fi
}

equals() {
  if [ -f "$1" -a -f "$2" ] ; then
    diff -q "$1" "$2" > /dev/null
  else
    return 1
  fi
}

overwrite_changed() {
  cat > .tmp
  if ! equals .tmp "$1" ; then
    cp .tmp "$1"
  fi
  rm .tmp
}

check_git_clean() {
  local BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  if [ "master" != "$BRANCH" ] ; then
    echo "Have you merged your changes to master? (currently on $BRANCH)"
    return 1
  fi

  local CHANGES="$(git status --porcelain)"
  if [ "" != "$CHANGES" ] ; then
    echo "Have you committed all local changes?

Changes:
$CHANGES"
    return 1
  fi

  local BEHIND="$(git rev-list --count @{upstream}..HEAD)"
  if [ "0" != "$BEHIND" ] ; then
    echo "Have you pushed everything to upstream? ($BEHIND commits behind upstream)"
    return 1
  fi
}

PAKET=.paket/paket.exe

paket_bootstrap() {
  if did paket_bootstrap ; then return 0 ; fi
  $RUN .paket/paket.bootstrapper.exe -s --max-file-age=60
  if [ ! -x $PAKET ] ; then
    chmod +x $PAKET
  fi
}

paket() {
  paket_bootstrap
  $RUN $PAKET "$@"
}

################################################################################

PROJECT_URL="https://github.com/Hopac/Hopac"
SUMMARY="A library for Higher-Order, Parallel, Asynchronous and Concurrent programming in F#."
DESCRIPTION="Inspired by languages like Concurrent ML and Cilk, Hopac is a library for F# with the aim of making it easier to write efficient parallel, asynchronous, concurrent and reactive programs. Hopac is licensed under a MIT-style license. See project website for further information."
COMPANY="Housemarque Inc."
COPYRIGHT="© $COMPANY"
TAGS="f#, fsharp, parallel, async, concurrent, reactive"
LICENSE_URL="$PROJECT_URL/blob/master/LICENSE.md"
ICON_URL="https://avatars2.githubusercontent.com/u/10173903"

################################################################################

if [ -n "$HOPAC_STRONG_NAME" ] ; then
  KEYFILE="../../Hopac.snk"
  PUBLICKEY="0024000004800000140100000602000000240000525341310008000011000000934bdab527f7c1b75f64288d92ffc72e2cdba9823589c12f246bcb15f6873124bf501cc1b90c1166881c41b2e871617e6a9e5bd45a95989a9e71b37fd3f6c85f589a1cd70a76ad7f9206bcc96497bef5e73820ca2f304c6c918faf9317f65dcc3fc6b7a8dac0d1c2dfa33df5475fd6a8a1c59be83c3f6a000e6f5590a632ef06a54f25874d96c8eac1754e1c384d120e64242e080da9b4c241e498890e40d36f56ca962adc11a06e3f0906344a6dbdc42ca489ea71ae837616aaf8c5e98d6a26ed7b3cf0d6842ffeb0eb528fc9c006f9cfbd3097564e14ae8491e3ffabeaffa04376b6f53fa56936471c2a0919542984f5e401984cd359cf80d7b3f5f6520689"
  NUPKG_ID="Hopac.StrongName"
else
  KEYFILE=""
  PUBLICKEY=""
  NUPKG_ID="Hopac"
fi

################################################################################

VERSION="$(cat RELEASE_NOTES.md                |
           grep -e '^#### '                    |
           sed -e 's/^#### *\([^ ]*\) .*/\1/g' |
           head -n 1)"

N="$(cat RELEASE_NOTES.md           |
     grep -n -e '^ *$'              |
     sed -e 's#^\([0-9]*\).*$#\1#g' |
     head -n 1)"

NOTES="$(cat RELEASE_NOTES.md         |
         head -n $((N-1))             |
         sed -e 's#^\(.*\)$#    \1#g' |
         tail -n $((N-2)))"

################################################################################

if [ -z "$SOLUTIONS" ] ; then
  if [ -z "$RUN" ] ; then
    SOLUTIONS="Hopac.sln Todo.sln"
  else
    SOLUTIONS="Hopac.sln"
  fi
fi

if [ -z "$CONFIGS" ] ; then
  CONFIGS="Debug Release"
fi

################################################################################

clean() {
  if did clean ; then return 0 ; fi

  find Libs -name bin | xargs rm -rf
  find Libs -name obj | xargs rm -rf

  rm -rf .gh-pages
  rm -rf .nuget
  rm -rf .paket/paket.exe
  rm -rf packages
}

restore() {
  if did restore ; then return 0 ; fi

  paket --silent restore
}

attrs() {
  local ATTRS="AssemblyTitleAttribute(\"$1\")
AssemblyProductAttribute(\"$1\")
AssemblyDescriptionAttribute(\"$SUMMARY\")
AssemblyVersionAttribute(\"$VERSION\")
AssemblyFileVersionAttribute(\"$VERSION\")
AssemblyCompanyAttribute(\"$COMPANY\")
AssemblyCopyrightAttribute(\"$COPYRIGHT\")
"

  if [ "$LIB" = "Hopac.Core" ] ; then
    if [ -n "$PUBLICKEY" ] ; then
      ATTRS="InternalsVisibleToAttribute(\"Hopac, PublicKey=$PUBLICKEY\")
InternalsVisibleToAttribute(\"Hopac.Platform, PublicKey=$PUBLICKEY\")
$ATTRS"
    else
      ATTRS="InternalsVisibleToAttribute(\"Hopac\")
InternalsVisibleToAttribute(\"Hopac.Platform\")
$ATTRS"
    fi
  fi

  if [ -n "$KEYFILE" ] ; then
    ATTRS="AssemblyKeyFileAttribute(\"$KEYFILE\")
$ATTRS"
  fi

  echo -n "$ATTRS"
}

generate_infos() {
  if did generate_infos ; then return 0 ; fi

  for LIB in Hopac Hopac.Platform.Net ; do
    overwrite_changed Libs/$LIB/AssemblyInfo.fs <<EOF
// NOTE: This is a generated file.

namespace System

open System.Reflection

$(attrs $LIB | sed -e 's#^#[<assembly: #g' -e 's#$#>]#g')

do ()
EOF
  done

  for LIB in Hopac.Core ; do
    overwrite_changed Libs/$LIB/AssemblyInfo.cs <<EOF
// NOTE: This is a generated file.

using System.Reflection;
using System.Runtime.CompilerServices;

$(attrs $LIB | sed -e 's#^#[assembly: #g' -e 's#$#]#g')
EOF
  done
}

build() {
  if did build ; then return 0 ; fi

  restore
  generate_infos

  for SOLUTION in $SOLUTIONS ; do
    for CONFIG in $CONFIGS ; do
      $BUILD /nologo /verbosity:quiet /p:Configuration=$CONFIG $SOLUTION
    done
  done
}

build_nupkg() {
  if did build_nupkg ; then return 0 ; fi

  build

  mkdir -p .nuget
  local TEMPLATE=.nuget/Hopac.template
  overwrite_changed $TEMPLATE <<EOF
type file
id $NUPKG_ID
version $VERSION
summary $SUMMARY
description $DESCRIPTION
copyright Copyright 2015
authors $COMPANY
owners $COMPANY
tags $TAGS
projectUrl $PROJECT_URL
iconUrl $ICON_URL
licenseUrl $LICENSE_URL
releaseNotes
$NOTES
files
    ../Libs/Hopac.Core/bin/Release/Hopac.Core.*             ==> lib/net45
    ../Libs/Hopac/bin/Release/Hopac.*                       ==> lib/net45
    ../Libs/Hopac.Platform.Net/bin/Release/Hopac.Platform.* ==> lib/net45
dependencies FSharp.Core >= 3.1.2.5
EOF

  paket --silent pack output .nuget templatefile $TEMPLATE
}

generate_docs() {
  if did generate_docs ; then return 0 ; fi

  if [ ! -d .gh-pages ] ; then
    git clone -b gh-pages $PROJECT_URL .gh-pages
  fi

  ./FsiRefGen/run                \
      --out .gh-pages            \
      --name Hopac               \
      --icon $ICON_URL           \
      --version $VERSION         \
      --project-url $PROJECT_URL \
      --                         \
      Libs/Hopac/Hopac.fsi       \
      Libs/Hopac/Stream.fsi      \
      Libs/Hopac/TopLevel.fsi
}

tests() {
  if did tests ; then return 0 ; fi

  build

  for CONFIG in $CONFIGS ; do
    for TEST in $(ls Tests) ; do
      echo "$TEST ($CONFIG)"
      $RUN "Tests/$TEST/bin/$CONFIG/$TEST.exe"
      echo
    done
  done
}

publish_docs() {
  if did publish_docs ; then return 0 ; fi

  generate_docs

  pushd .gh-pages
  mkdir -p $VERSION
  cp *.html *.css *.js $VERSION/
  git add $VERSION/*
  git add *.html *.css *.js
  git commit -m "Updated docs for $VERSION"
  git push
  popd
}

publish_nupkg() {
  if did publish_nupkg ; then return 0 ; fi

  build_nupkg

  paket push url https://www.nuget.org file .nuget/Hopac.$VERSION.nupkg
}

tag_release() {
  if did tag_release ; then return 0 ; fi

  git tag -a $VERSION -m $VERSION
  git push --follow-tags
}

check_release_date() {
  local RELEASE_DATE="$(head -n 1 RELEASE_NOTES.md | sed -e 's#.* \(.*-.*-.*\)$#\1#g')"
  local CURRENT_DATE="$(date '+%Y-%m-%d')"

  if [ "$RELEASE_DATE" != "$CURRENT_DATE" ] ; then
    echo "Release notes specify date as $RELEASE_DATE, but current date is $CURRENT_DATE."
    return 1
  fi
}

publish() {
  if did publish ; then return 0 ; fi

  check_git_clean

  clean
  build
  generate_docs
  build_nupkg
  tests

  check_git_clean

  if [ -z "$KEYFILE" ] ; then
    cat <<EOF

You are about to publish Hopac.

Version: $VERSION

Release notes:
$NOTES

EOF
    check_release_date

    read -p "Enter Y to proceed: " INPUT
    if [ "$INPUT" != "Y" ] ; then
      return 1
    fi

    publish_nupkg
    publish_docs
    tag_release
  else
    echo
    echo "You may publish .nuget/$NUPKG_ID.$VERSION.nupkg manually."
  fi
}

repl() {
  SOLUTIONS=Hopac.sln
  CONFIGS=Release
  build

  rlwrap -t dumb $FSI --use:Hopac.fsx
}

benchmarks() {
  SOLUTIONS=Hopac.sln
  CONFIGS=Release
  build

  for BENCHMARK in $(ls Benchmarks) ; do
    echo "$BENCHMARK"
    $RUN "Benchmarks/$BENCHMARK/bin/Release/$BENCHMARK.exe"
    echo
  done
}

pull_submodules() {
  git submodule foreach git pull origin master
}

watch() {
  echo "watch: $*"

  fswatch --latency 2              \
          -0                       \
          --exclude '\.gh-pages.*' \
          --exclude '\.nuget.*'    \
          --exclude '\.paket.*'    \
          --exclude '\.tmp.*'      \
          --exclude '\.git.*'      \
          --exclude 'packages.*'   \
          --exclude '.*#.*'        \
          --exclude '.*/bin.*'     \
          --exclude '.*/obj.*'     \
          --exclude '.*\.proj'     \
          .                        \
  | nice xargs -0 -t -n 1 -I {} ./run $*

  exit
}

################################################################################

while [ $# != 0 ] ; do
  COMMAND="$1"
  shift
  case "$COMMAND" in
    "-x")              set -x ;;
    "benchmarks")      benchmarks ;;
    "build")           build ;;
    "build_nupkg")     build_nupkg ;;
    "clean")           clean ;;
    "generate_docs")   generate_docs ;;
    "pull_submodules") pull_submodules ;;
    "publish")         publish ;;
    "publish_docs")    publish_docs ;;
    "repl")            repl ;;
    "restore")         restore ;;
    "tests")           tests ;;
    "watch")           watch "$@" ;;
    *)
      echo "Unknown command: '$COMMAND'

If you are using Bash, you can execute

  source run.complete

to get autocompletion for this script."
      exit 1
      ;;
  esac
done
