// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Hopac.Core")]
[assembly: AssemblyProductAttribute("Hopac.Core")]
[assembly: AssemblyDescriptionAttribute("A library for Higher-Order, Parallel, Asynchronous and Concurrent programming in F#.")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]
[assembly: AssemblyCompanyAttribute("Housemarque Inc.")]
[assembly: AssemblyCopyrightAttribute("� Housemarque Inc.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
    }
}
