// Auto-Generated by FAKE; do not edit
namespace Hopac.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.Platform.fsproj")>]
[<assembly: AssemblyProductAttribute("Hopac.Platform.fsproj")>]
[<assembly: AssemblyVersionAttribute("0.4.1")>]
[<assembly: AssemblyFileVersionAttribute("0.4.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.Platform.fsproj"
    let [<Literal>] AssemblyProduct = "Hopac.Platform.fsproj"
    let [<Literal>] AssemblyVersion = "0.4.1"
    let [<Literal>] AssemblyFileVersion = "0.4.1"
